<?php
session_start();
include 'includes/config.php';
$id = $_GET['id'];
$sql = mysqli_query($con, "SELECT * FROM medication WHERE patient_id = '$id'");

require '../fpdf/fpdf.php';
class PDF extends FPDF{
  function Footer(){
    $this->SetY(-15);
    $this->SetFont('Arial','I',8);
    $this->Cell(0,10,$this->PageNo(),0,0,'C');
  }
}

$pdf = new PDF('P','mm','A4');
$pdf->AddPage();
$pdf->SetY(20);
$pdf->Image('../img/logo.png',92,10,-200);
$pdf->Ln(15);
$pdf->SetFont('Arial','B',14);
$pdf->Cell(189,6,'HEALTH CARE MANAGEMENT SYSTEM',0,1,'C');
$pdf->SetFont('Arial','',10);
$pdf->Cell(189,5,'P.O.BOX 123, Tel: +255 224 556 225, Fax: +255 224 556 225, CHWAKA-ZANZIBAR',0,1,'C');
$pdf->Ln(5);

$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,10,'PATIENT\'S FINAL REPORTS',0,1,'C');
$pdf->SetFont('Arial','B',12);

// PATIENT INFO
$info = mysqli_query($con, "SELECT * FROM patient INNER JOIN sick_description ON patient.patient_id = sick_description.patient_id WHERE patient.patient_id = '$id'");
$row = mysqli_fetch_assoc($info);
$pdf->Ln(10);

$pdf->Cell(95,8,"PATIENT'S BASIC INFORMATION",0,0);
$pdf->Cell(95,8,"PATIENT'S ADDRESS INFORMATION",0,1);

$pdf->SetFont('Arial','',12);

$pdf->Cell(30,8,'Patient Name',0,0);
$pdf->Cell(65,8,': '.$row['fname'].' '.$row['lname'],0,0);

$pdf->Cell(30,8,'Phone Number',0,0);
$pdf->Cell(65,8,': '.$row['phone'],0,1);

$pdf->Cell(30,8,'Age',0,0);
$pdf->Cell(65,8,': '.patient_age($row['dob']),0,0);

$pdf->Cell(30,8,'E-Mail Address',0,0);
$pdf->Cell(65,8,': '.$row['email'],0,1);

//Patient Desesase
$pdf->Cell(30,8,'Desease',0,0);
$pdf->Cell(65,8,': '.$row['problem'],0,0);

$pdf->Cell(30,8,'Street Address',0,0);
$pdf->Cell(65,8,': '.$row['address'],0,1);

$pdf->Ln(5);
// LAB RESULTS TABLE
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,'LAB RESULTS',0,1,'C');

$pdf->SetFont('Arial','B',12);
$pdf->Cell(18,7,'Malaria',1,0);
$pdf->Cell(15,7,'TB',1,0,'C');
$pdf->Cell(15,7,'HIV',1,0,'C');
$pdf->Cell(28,7,'B. Group',1,0,'C');
$pdf->Cell(18,7,'U.T.I',1,0,'C');
$pdf->Cell(18,7,'U.T.P',1,0,'C');
$pdf->Cell(20,7,'Pressure',1,0,'C');
$pdf->Cell(20,7,'Weight',1,0,'C');
$pdf->Cell(20,7,'Height',1,0,'C');
$pdf->Cell(20,7,'Allergy',1,1,'C');

$pdf->SetFont('Arial','',12);
$lab = mysqli_query($con, "SELECT * FROM lab_results WHERE patient_id = '$id' ORDER BY id DESC");
  $res = mysqli_fetch_array($lab);
  $pdf->Cell(18,7,$res[2],1,0,"C");
  $pdf->Cell(15,7,$res[3],1,0,'C');
  $pdf->Cell(15,7,substr($res[4],0,3),1,0,'C');
  $pdf->Cell(28,7,$res[5],1,0,'C');
  $pdf->Cell(18,7,$res[6],1,0,'C');
  $pdf->Cell(18,7,$res[7],1,0,'C');
  $pdf->Cell(20,7,$res[8],1,0,'C');
  $pdf->Cell(20,7,$res[9],1,0,'C');
  $pdf->Cell(20,7,$res[10],1,0,'C');
  $pdf->Cell(20,7,$res[11],1,1,'C');



// MEDICAL INFO TABLE
$pdf->Ln(10);
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,8,'MEDICAL INFORMATION',0,1,'C');

$pdf->SetFont('Arial','B',12);
$pdf->Cell(40,7,'Medicine Name',1,0);
$pdf->Cell(25,7,'Quantity',1,0,'C');
$pdf->Cell(25,7,'Dosage',1,0,'C');
$pdf->Cell(25,7,'Total Cost',1,0,'C');
$pdf->Cell(75,7,'Comments',1,1,'C');

$pdf->SetFont('Arial','',12);

while($data = mysqli_fetch_assoc($sql)){
  $pdf->Cell(40,7,$data['med_name'],1,0);
  $pdf->Cell(25,7,$data['med_qty'],1,0,'C');
  $pdf->Cell(25,7,$data['dosage'],1,0,'C');
  $pdf->Cell(25,7,number_format($data['cost']).' ',1,0,'R');
  $pdf->Cell(75,7,' '.$data['comments'],1,1);
}

$pdf->Ln(10);
$pdf->Cell(50,8,'Total Cost',0,0);
$pdf->Cell(100,8,': '.number_format($_GET['cost'],2).' Tsh',0,1);
$pdf->Cell(50,8,'Discount',0,0);
$pdf->Cell(100,8,': '.number_format($_GET['disc'],2).' Tsh',0,1);
$pdf->Cell(50,8,'Amount Paid',0,0);
$pdf->Cell(100,8,': '.number_format($_GET['net'],2).' Tsh',0,1);

$pdf->Ln(10);
$pdf->Cell(0,8,'This report is generated by '.strtoupper($_SESSION['username']).' at '.date('d-m-Y'),0,1);

$pdf->Ln(15);
$pdf->Cell(0,8,'Signature',0,1,'R');
$pdf->Cell(0,8,'...............',0,1,'R');





$pdf->Output('','pharmacy_report.pdf');


// Age function
function patient_age($dob){
  $now = date('Y-m-d');
  $sd = new DateTime($dob);
  $ed = new DateTime($now);

  $diff = $sd->diff($ed);
  $age = $diff->format('%y');
  return $age;
}